# Produce list of submissions associated with a cell/replicate
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX ucscSubmission:<http://jumpgate.caltech.edu/wiki/UcscSubmissionOntology#>
PREFIX libraryOntology:<http://jumpgate.caltech.edu/wiki/LibraryOntology#>

SELECT distinct ?liburn ?cell ?replicate ?subid ?name ?submission_date
WHERE {
    ?subid ucscSubmission:name ?name ;
           ucscSubmission:library_urn ?liburn ;
           libraryOntology:date ?submission_date.
    ?liburn libraryOntology:cell_line ?cell ;
            libraryOntology:replicate ?replicate ;
            libraryOntology:species_name ?species .
    OPTIONAL { ?liburn libraryOntology:treatement ?treatment . }
    FILTER(regex(?species, "Homo sapiens", "i"))
    #filter(?submission_date > "2011-04-01T00:00:00Z"^^xsd:dateTime)
    #filter(!bound(?liburn))
}
ORDER BY ?cell ?replicate ?liburn ?submission_date
