# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=64)),
                ('regex', models.CharField(max_length=1024)),
                ('url_template', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('model', models.CharField(choices=[('Zebra ZM400', 'Zebra ZM400'), ('Zebra ZM600', 'Zebra ZM600')], max_length=64)),
                ('ip_address', models.GenericIPAddressField()),
                ('label_shape', models.CharField(choices=[('Square', 'Square'), ('Circle', 'Circle')], max_length=32)),
                ('label_width', models.FloatField(help_text='width or diameter in inches')),
                ('label_height', models.FloatField(help_text='height in inches')),
                ('notes', models.TextField()),
            ],
        ),
    ]
