PREFIX libraryOntology: <http://jumpgate.caltech.edu/wiki/LibraryOntology#>
PREFIX submissionOntology: <http://jumpgate.caltech.edu/wiki/UcscSubmissionOntology#>
PREFIX ucscDaf: <http://jumpgate.caltech.edu/wiki/UcscDaf#>
PREFIX ncbiTaxon: <http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=>
PREFIX geoSoft: <http://www.ncbi.nlm.nih.gov/geo/info/soft2.html#>

select distinct ?filename, ?md5sum, ?file_type ?file_type_label
WHERE {
  <{{submission}}> ucscDaf:has_file ?file ;
                   a submissionOntology:submission .

  ?file ucscDaf:filename ?filename ;
        ucscDaf:md5sum ?md5sum ;
        a ?file_type .
  ?file_type a <{{file_class}}> ;
             geoSoft:fileTypeLabel ?file_type_label .

}