# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('barcode', models.CharField(blank=True, max_length=200, null=True)),
                ('creator', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LabelPrinter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('model', models.CharField(default='ZM400', max_length=64)),
                ('ip_address', models.GenericIPAddressField()),
                ('labels', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('ZPL_code', models.TextField(verbose_name='template')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.LabelPrinter')),
            ],
        ),
        migrations.AddField(
            model_name='labelcontent',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.LabelTemplate'),
        ),
    ]
