#!/usr/bin/env python
import sys
from gaworkflow.pipeline.configure_run import *

def main(args=None):
  ci = ConfigInfo()

  flowcell = 'FC12150'
  cfg_filepath = 'config32auto.txt'
  genome_dir = '/home/king/trog_drive/'

  status_retrieve_cfg = retrieve_config(ci, flowcell, cfg_filepath, genome_dir)
  if status_retrieve_cfg:
    print "Retrieve config file successful"
  else:
    print "Failed to retrieve config file"
  #ci.config_filepath = 'config32bk.txt'

  if status_retrieve_cfg:
    status = configure(ci)
    if status:
      print "Configure success"
    else:
      print "Configure failed"
    
    print 'Run Dir:', ci.run_path
    print 'Bustard Dir:', ci.bustard_path
    
    if status:
      print 'Running pipeline now!'
      run_status = run_pipeline(ci)
      if run_status is True:
        print 'Pipeline ran successfully.'
        return 0
      else:
        print 'Pipeline run failed.'
        return 1

    return 2

if __name__ == "__main__":
  sys.exit(main(sys.argv[1:]))
