#!/usr/bin/env python
import sys
from gaworkflow.pipeline.retrieve_config import *

def main(args=None):
  #Display help if no args are presented
  if len(sys.argv) == 1:
    sys.argv.append('-h')
    
  options = getCombinedOptions()
  msg_list = ['ERROR MESSAGES:']
  if options.output_filepath is None:
    msg_list.append("  Output filepath argument required. -o <filepath> or --output=<filepath>")
    
  if options.flowcell is None:
    msg_list.append("  Flow cell argument required. -f <flowcell> or --flowcell=<flowcell>")
    
  if options.url is None:
    msg_list.append("  URL argument required (-u <url> or --url=<url>), or entry\n" \
                    "    in /etc/ga_frontend/ga_frontend.conf or ~/.ga_frontend.conf")
    
  if len(msg_list) > 1:
    print '\n'.join(msg_list)
    return 1
  
  saveConfigFile(options.flowcell, options.url, options.output_filepath)
  return 0
  
if __name__ == "__main__":
  sys.exit(main(sys.argv[1:]))
